# Python print() function
* Giới thiệu hàm prrint() cơ bản

In [2]:
?print

Docstring:

`print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)`

Prints the values to a stream, or to `sys.stdout` by default.

Optional keyword arguments:
* file:  a file-like object (stream); defaults to the current `sys.stdout`.
* sep:   string inserted between values, default a space.
* end:   string appended after the last value, default a newline.
* flush: whether to forcibly flush the stream.
* Type:      builtin_function_or_method

# Exercise1: Viết function tìm thể tích
* Hình lập phương
* Hình hộp chữ nhật
* Hình trụ tròn
* Hình cầu

Viết 4 functions thực hiện tính thể tích của các khối sau:
* Hình lập phương $𝑽 = 𝒔^𝟑$ (s là độ dài của cạnh)
    + input function: s
    + output function: V

* Hình hộp chữ nhật $𝑽 = 𝒍 ∗ 𝒘 ∗ 𝒉$ (l là chiều dài, w là chiều rộng, h: là chiều cao)
    + input function: l, w, h
    + output function: V
* Hình trụ tròn: $𝑽 = \pi ∗ 𝒓^𝟐 ∗ 𝒉$ (r là bán kính đáy, h là chiều cao)
    + input function: r, h
    + output function: V
* Hình cầu: $𝑽 = \displaystyle\frac{𝟒}{𝟑} ∗ \pi ∗ 𝒓^𝟑$ (r bán kính hình cầu)
    + input function: r
    + output function: V

NOTE: Tùy thuộc vào giá trị 𝜋 các bạn định nghĩa mà kết quả có thể sai lệch. Ví dụ tự định nghĩa `𝜋 = 3.14` hoặc dùng math.pi `𝜋 = 3.141592653589793`

In [63]:
import math

def calc_cube_volume(s):
    return s ** 3

def calc_rectangular_prism_volumn(l,w,h):
    return l * w * h

def calc_cylinder_volume(r,h):
    PI = 3.14 # math.pi
    return PI * r**2 * h

def calc_globular_volume(r):
    PI = 3.14 # math.pi
    return (4 / 3) * PI * r**3

In [59]:
assert calc_cube_volume(s=2)==8
calc_cube_volume(3)

27

In [61]:
assert calc_rectangular_prism_volumn(2,2,3) == 12
calc_rectangular_prism_volumn(1,2,3)

6

In [66]:
assert calc_cylinder_volume(1.5,4) == 28.26
print(round(calc_cylinder_volume(1.2, 4),2))

18.09


In [68]:
assert round(calc_globular_volume(1),2) == 4.19
print(round(calc_globular_volume(1.3),2))

9.2


# Exercise2: Viết function đánh giá classification model bằng f1-score
![w01_exersise2](../../../../images/2023AIO/w01_exersise2.PNG)

In [76]:
def calc_f1_score(tp, fp, fn):
    if type(tp) is not int:
        print("tp must be int")
        return
    if type(fp) is not int:
        print("fp must be int")
        return
    if type(fn) is not int:
        print("fn must be int")
        return
        
    if tp <= 0 or fp <= 0 or fn <= 0:
        print("tp and fp and fn must be greater than zero")
        return
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1_score = 2 * precision * recall / (precision + recall)
    
    print(f"precision is {precision}")
    print(f"recall is {recall}")
    print(f"f1-score is {f1_score}")
    
    return f1_score

In [11]:
calc_f1_score(2,3,4)

precision is 0.4
recall is 0.3333333333333333
f1-score is 0.3636363636363636


(0.4, 0.3333333333333333, 0.3636363636363636)

In [12]:
calc_f1_score('a',3,4)

tp must be int


In [13]:
calc_f1_score(2,'a',4)

fp must be int


In [14]:
calc_f1_score(2,3,'a')

fn must be int


In [15]:
calc_f1_score(2,3,0)

tp and fp and fn must be greater than zero


In [16]:
calc_f1_score(2.1,3,4)

tp must be int


In [77]:
assert round(calc_f1_score(2,3,5),2) == 0.33
print(round(calc_f1_score(2,4,5),2))

precision is 0.4
recall is 0.2857142857142857
f1-score is 0.3333333333333333
precision is 0.3333333333333333
recall is 0.2857142857142857
f1-score is 0.30769230769230765
0.31


# Exercise3: Viết function tính kết quả theo các activtion function
* Binary Step Function
* Sigmoid Function
* Elu Function

![w01_exersise3](../../../../images/2023AIO/w01_exersise3.PNG)

In [78]:
def is_number(x):
    try:
        float(x)
    except ValueError:
        return False
    return True

assert is_number(3) == 1.0
assert is_number('-2a') == 0.0
print(is_number(1))
print(is_number('n'))

True
False


In [86]:
def is_number(x):
    try:
        float(x)
    except ValueError:
        return False
    return True

def calc_activation(x,act_name):  
    #x = input("Input x = ")
    if not is_number(x):
        print("x must be a number")
        return
    
    #func = input("Input activation function (binary|sigmoid|elu): ").lower()
    act_name = act_name.lower()
    if (act_name != "binary") and (act_name != "sigmoid") and (act_name != "elu"):
        print(f"{act_name} is not supportted")
        return
    
    x = float(x)
    if act_name == "binary":
        if x < 0:
            return 0
        else:
            return 1
    elif act_name == "sigmoid":
        return 1 / (1 + math.exp(-x))
    elif act_name == "elu":
        alpha = 0.01
        if x < 0:
            return alpha * (math.exp(x) - 1)
        else:
            return x
    

In [36]:
calc_activation()

Input x = 1.5
Input activation function (binary|sigmoid|elu): binary


1

In [37]:
calc_activation()

Input x = 1.5
Input activation function (binary|sigmoid|elu): sigmoid


0.8175744761936437

In [38]:
calc_activation()

Input x = abc
x must be a number


In [39]:
calc_activation()

Input x = 1.5
Input activation function (binary|sigmoid|elu): relu
relu is not supportted


In [87]:
assert float(calc_activation(4, 'binary')) == 1.0
assert float(calc_activation(-7, 'binary')) == 0.0
print( calc_activation(2, 'binary'))
print( calc_activation(-1, 'binary'))

1
0


In [83]:
assert round(calc_activation(3, 'sigmoid'),2) == 0.95
print( round(calc_activation(2, 'sigmoid'),2))

0.88


In [84]:
assert round(calc_activation(1, 'elu')) == 1
print( round(calc_activation(-1, 'elu'),2))

-0.01


In [88]:
assert calc_activation(1, 'binary') == 1
print( round(calc_activation(3, 'sigmoid'),2))

0.95


# Exercise4: Viết function tính loss theo regression loss function
* Mean Absolute Error (MAE)
* Mean Square Error (MSE)
* Root Mean Square Error (RMSE)

![w01_exersise4](../../../../images/2023AIO/w01_exersise4.PNG)

In [89]:
import random

def calc_mae(y, y_hat):
    return abs(y - y_hat)

def calc_mse(y, y_hat):
    return (y - y_hat) ** 2

def calc_regression_loss():  
    num_samples = input("Input number of samples (integer number) which are generated: ")
    if not num_samples.isnumeric():
        print("number of samples must be an integer number")
        return
    
    loss_name = input("Input loss name (MAE|MSE|RMSE): ").upper()
    if (loss_name != "MAE") and (loss_name != "MSE") and (loss_name != "RMSE"):
        print(f"{func} is not supportted")
        return
    
    num_samples = int(num_samples)
    final_loss = 0
    for i in range (0, num_samples):
        predict_i = random.uniform(0,10) #random.randint(0,10)
        target_i = random.uniform(0,10)  #random.randint(0,10)
        loss_i = 0
        if loss_name == "MAE":
            loss_i = calc_mae(predict_i, target_i)
        elif loss_name == "MSE" or loss_name == "RMSE":
            loss_i = calc_mse(predict_i, target_i)
        final_loss += loss_i
        
        print(f"loss name: {loss_name}, sample: {i}, pred: {predict_i}, target: {target_i}, loss: {loss_i}")
        
    final_loss /= num_samples
    if loss_name == "RMSE":
        final_loss = math.sqrt(final_loss)
    
    print(f"final RMSE: {final_loss}")

In [90]:
y = 1
y_hat = 6
assert calc_mae(y, y_hat)==5

y = 2
y_hat = 9
print(calc_mae(y, y_hat))

7


In [92]:
y = 4
y_hat = 2
assert calc_mse(y, y_hat)==4
print(calc_mse(2, 1))

1


In [45]:
calc_regression_loss()

Input number of samples (integer number) which are generated: 5
Input loss name (MAE|MSE|RMSE): RMSE
loss name: RMSE, sample: 0, pred: 2.8449821963834134, target: 2.4451262490367442, loss: 0.15988477862850228
loss name: RMSE, sample: 1, pred: 1.5076574668887988, target: 7.254973226675668, loss: 33.03163844269452
loss name: RMSE, sample: 2, pred: 5.936577996361759, target: 1.9836211799304093, loss: 15.62586759257107
loss name: RMSE, sample: 3, pred: 1.1824254362188136, target: 1.121640502434983, loss: 0.003694808175104677
loss name: RMSE, sample: 4, pred: 9.353525484361642, target: 3.9589918517132103, loss: 29.100993113775083
final RMSE: 3.9477101903722436


# (Optional) Exercise5: Viết function thực hiện tính Pascal’s Triangle và Fibonacci Sequence
![w01_exersise5](../../../../images/2023AIO/w01_exersise5.PNG)
![w01_exersise52](../../../../images/2023AIO/w01_exersise52.PNG)
![w01_exersise53](../../../../images/2023AIO/w01_exersise53.PNG)

## Pascal’s Triangle
* Input: level là số lượng hàng
* Output: Print ra kết quả từng hàng theo Pascal’s Triangle

In [55]:
import numpy as np

def print_pascal_triangle(level=5):
    arr_number = np.array([1])
    for i in range(1,level+1):
        print(arr_number, sep=' ')
        arr_number_next_level = np.array([1])
        
        if i == 0:
            continue
        if i == 1:
            arr_number = np.append(arr_number,[1])
            continue
            
        for j in range(0, len(arr_number) - 1):
            arr_number_next_level = np.append(arr_number_next_level, arr_number[j] + arr_number[j+1])
            
        arr_number_next_level = np.append(arr_number_next_level,[1])
        
        arr_number = arr_number_next_level

In [63]:
print_pascal_triangle(6)

[1]
[1 1]
[1 2 1]
[1 3 3 1]
[1 4 6 4 1]
[ 1  5 10 10  5  1]


## Fibonacci Sequence
* Input: length là độ dài của chuỗi Fibonacci
* Output: Print ra kết quả các element trong chuỗi Fibonacci
* Các bạn nên tìm hiểu các công thức có thể thực hiện được Pascal’s Triangle và Fibonacci Sequence

In [78]:
import numpy as np

def print_fibonacci(length=5):
    arr_number = np.array([0])
    for i in range(0, length):
        if i == 0:
            continue
        if i == 1:
            arr_number = np.append(arr_number, [1])
            continue
            
        arr_number = np.append(arr_number, arr_number[len(arr_number)-1] + arr_number[len(arr_number)-2])
        
    print(arr_number, sep=' ')

In [80]:
print_fibonacci(9)

[ 0  1  1  2  3  5  8 13 21]


# (Optional) Exerices6: Viết function xấp xỉ các hàm lượng giác
![w01_exersise6](../../../../images/2023AIO/w01_exersise6.PNG)

Viết 4 functions để ước lượng các hàm số sau.
* Input: x (số muốn tính toán) và n (số lượng bậc muốn xấp xỉ)
* Output: Kết quả ước lượng hàm tương ứng với x. Ví dụ hàm cos(x=0) thì output = 1

NOTE:
* x là radian
* n là số nguyên dương ≥ 0
* các bạn nên viết một hàm tính giai thừa riêng

In [103]:
def calc_giaithua(n):
    result = 1
    for i in range (1, n+1):
        result *= i
    #print(f"{n}!={result}")
    return result

def sin(x, n):
    sin_result = 0
    for i in range (0, n):
        value_i = ((-1) ** i) * (x ** (2 * i + 1)) / calc_giaithua(2 * i + 1)
        sin_result += value_i
    
    return sin_result

def cos(x, n):
    cos_result = 0
    for i in range (0, n):
        cos_result += ((-1) ** i) * (x ** (2 * i)) / calc_giaithua(2 * i)
    
    return cos_result

def sinh(x, n):
    sinh_result = 0
    for i in range (0, n):
        sinh_result += (x ** (2 * i + 1)) / calc_giaithua(2 * i + 1)
    
    return sinh_result

def cosh(x, n):
    cosh_result = 0
    for i in range (0, n):
        cosh_result += (x ** (2 * i)) / calc_giaithua(2 * i)
    
    return cosh_result

In [104]:
sin(3.14, 10)

0.001592652393160744

In [105]:
assert round(cos(1, 10), 2) == 0.54
print(round(cos(3.14, 10),2))

-1.0


In [108]:
assert round(sin(1, 10), 4) == 0.8415
print(round(sin(3.14, 10),4))

0.0016


In [110]:
assert round(sinh(1, 10), 2) == 1.18
print(round(sinh(3.14, 10),2))

11.53


In [111]:
assert round(cosh(1, 10), 2) == 1.54
print(round(cosh(3.14, 10),2))

11.57


In [20]:
cos(3.14,10)

0!=1
2!=2
4!=24
6!=720
8!=40320
10!=3628800
12!=479001600
14!=87178291200
16!=20922789888000
18!=6402373705728000


-0.9999987352210833

In [23]:
sinh(3.14, 10)

1!=1
3!=6
5!=120
7!=5040
9!=362880
11!=39916800
13!=6227020800
15!=1307674368000
17!=355687428096000
19!=121645100408832000


11.530292029865986

In [24]:
cosh(3.14, 10)

0!=1
2!=2
4!=24
6!=720
8!=40320
10!=3628800
12!=479001600
14!=87178291200
16!=20922789888000
18!=6402373705728000


11.573574824666185

# (Optional) Exercise7: Viết function đảo ngược các vị trí 1 số nguyên dương cho trước
![w01_exersise7](../../../../images/2023AIO/w01_exersise7.PNG)

* Input: n là một dãy số nguyên dương.
* Output: Đảo ngược vị trí các số trong n. Ví dụ input: 12345678910, output: 1987654321

NOTE: Các bạn chú ý các điều kiện sau
* Không được ép kiểu sang string
* Chỉ sử dụng while hoặc for loop

In [112]:
def reverse_number(n):
    arr = []
    is_finish = False
    while not is_finish:
        number_du = n % 10 
        number_nguyen = n // 10
        arr.append(number_du)
        if (number_nguyen == 0):
            is_finish = True
        n = number_nguyen
    
    rev_number = 0
    for i in range(0, len(arr)):
        rev_number = rev_number * 10 + arr[i]
    return rev_number

In [114]:
assert reverse_number(1234)==4321
assert reverse_number(34532)==23543
print(reverse_number(12))
print(reverse_number(123456789))

21
987654321


In [54]:
reverse_number(19876543210)

1234567891

In [55]:
reverse_number(123456789)

987654321

In [57]:
var1 = "This is var1"
var2 = 3
var3 = 15.5
print('var1= ', var1)
print(f'var1={var1}, var2={var2}, var3={var3}')

var1=  This is var1
var1=This is var1, var2=3, var3=15.5


In [69]:
tp = 'true'
if type(tp) != int: # isinstance(tp, int)
    print('tp must be int')

tp must be int


In [70]:
fp = 1
if type(fp) != int: # isinstance(fp, int)
    print('fp must be int')

In [71]:
fn = 'One'
if type(fn) != int: # isinstance(fp, int)
    print('fn must be int')

fn must be int


In [72]:
tp = 10
fp = -1
fn = 1
if not ((tp > 0) and (fn > 0) and (fp > 0)):
    print('tp and fp and fn must be greater than zero')

tp and fp and fn must be greater than zero


In [94]:
value1 = 10
value2 = 20
value3 = 30
print(value1, end=' ')
print(value2, end=' ')
print(value3, end=' ')

10 20 30 

In [96]:
def test1(level):
    for lv in range(level):
        for i in range(lv + 1):
            print(i, end=' ')
        print()
        
test1(5)

0 
0 1 
0 1 2 
0 1 2 3 
0 1 2 3 4 


In [97]:
for row in range(4):
    print(row)

0
1
2
3


In [115]:
def test2(length):
    count = 0
    n1, n2 = 0, 1
    while count < length:
        print(n1, end=' ')
        nth = n1 + n2
        n1 = n2
        n2 = nth
        count += 1
test2(length=8)

0 1 1 2 3 5 8 13 