# Numpy Arrays
A NumPy array is simply a grid that contains values of the same type. NumPy Arrays come in two forms; **Vectors** and **Matrices**. Vectors are strictly one-dimensional(1-d) arrays, while Matrices are multidimensional. In some cases, Matrices can still have only one row or one column.


**Python objects**
* high-level number objects: integers, floating point
* containers: lists (costless insertion and append), dictionaries (fast lookup)

**NumPy provides**
* extension package to Python for multi-dimensional arrays
* closer to hardware (efficiency)
* designed for scientific computation (convenience)
* Also known as array oriented computing

**Why it is useful**: Memory-efficient container that provides fast numerical operations

In [3]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

***If you got an error while running the above cell, import it by using the following command***


***`!pip3 install numpy`***

In [2]:
# check verison of the numpy library
np.__version__

'1.22.0'

# Creating Arrays

## Creating One dimensional array

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 


**Convert lists or tuples to arrays using `np.array()`**

In [11]:
# Convert lists or tuples to arrays using np.array()
# Note that np.array(2, 5, 6, 7) will throw an error - you need to pass a list or a tuple
array_from_list = np.array([2, 5, 6, 7]) 
array_from_tuple = np.array((4, 5, 8, 9))

print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


If we add an element of string data type in a numpy array

In [3]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of all the elements.
np.array([1, 4, 2, '5', 3, False])

array(['1', '4', '2', '5', '3', 'False'], dtype='<U11')

## Create a matrix using numpy

In [4]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
# MATRIX
a = np.array(a)

In [4]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

Create matrix using np.array function - **combine row by row**

In arrays unlike lists you can only have one type of element and this is very similar to matrix, 

In [ ]:
A = np.array([[1,2,3],[10,20,30],[100,200,300]]) # Pass in a list of lists to create a multidimensional array.
A.ndim

In [ ]:
r1 = ["I", "am", "happy"]
r2 = ["What", "a", "day"]
r3 = [1, 2, 3]
np.array([r1, r2, r3])
# U5 stands for Unicode 5 characters

In [ ]:
array_2D = np.array([(3,4,6),(2,1,6)])
array_2D

In [ ]:
m = np.array([[7, 8, 9], [10, 11, 12]]) # 2x3 array
m

Create array containing complex numbers

In [19]:
cplxMatrix = np.array([[2,4], [3,6],[4,8]], dtype=complex)
cplxMatrix

array([[2.+0.j, 4.+0.j],
       [3.+0.j, 6.+0.j],
       [4.+0.j, 8.+0.j]])

## Create structured Arrays

In [21]:
emp_names = ['Danielle', 'Lorena', 'Manuel', 'Ryan', 'Teresa', 'Wes']
emp_ids = [1, 2, 3, 4, 5, 6]
emp_scores = [78.2, 57.50, 90, 77, 96.20, 87.7]

emp_data = np.zeros(6, dtype = {'names': ('Name', 'ID', 'Score'),
                               'formats':('U16', 'i4', 'f8')})
# U16: An unicode string of 16 characters
# i4: A 4-byte int (int32)
# f8: An 8-byte float (float64)
emp_data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.),
       ('', 0, 0.)],
      dtype=[('Name', '<U16'), ('ID', '<i4'), ('Score', '<f8')])

In [22]:
emp_data['Name'] = emp_names
emp_data['ID'] = emp_ids
emp_data['Score'] = emp_scores
emp_data

array([('Danielle', 1, 78.2), ('Lorena', 2, 57.5), ('Manuel', 3, 90. ),
       ('Ryan', 4, 77. ), ('Teresa', 5, 96.2), ('Wes', 6, 87.7)],
      dtype=[('Name', '<U16'), ('ID', '<i4'), ('Score', '<f8')])

In [23]:
# To view content of each column
emp_data['Name']

array(['Danielle', 'Lorena', 'Manuel', 'Ryan', 'Teresa', 'Wes'],
      dtype='<U16')

In [24]:
emp_data["ID"]

array([1, 2, 3, 4, 5, 6])

In [25]:
emp_data['Score']

array([78.2, 57.5, 90. , 77. , 96.2, 87.7])

In [26]:
emp_data[2]

('Manuel', 3, 90.)

In [27]:
emp_data[-2]

('Teresa', 5, 96.2)

In [28]:
emp_data[-2]['Score']

96.2

In [29]:
# Get all the employees whose score is greater than 85 in the test
emp_data[emp_data['Score'] > 85]['Name'] 

array(['Manuel', 'Teresa', 'Wes'], dtype='<U16')

## Creating arrays using built-in functions

The other common way is to initialise arrays. You do this when you know the size of the array beforehand.

The following ways are commonly used:
* `np.ones()`: Create array of 1s with the given shape and data type
* `np.ones_like`: Take another array and create a `ones` array of same shape and data type
* `np.zeros()`: Create array of 0s
* `np.zeros_like`: Take another array and create a `zeros` array of same shape and data type
* `np.arange()`: Create array with increments of a fixed step size. Create an array of evenly spaced values (step value)
* `np.linspace()`: Create array of fixed length. Create an array of evenly spaced values (number of samples)

### `ones`

In [12]:
# Tip: Use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

Create a matrix of `ones` of specific dimension.

In [9]:
# Creating a 5 x 3 array of ones
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Notice that, by default, numpy creates data type = float64
# Can provide dtype explicitly using dtype
np.ones((5, 3), dtype = np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### `ones_like`
`ones_like` is similar to `ones` but it get difference parameter. The input parameter is an array then this function returns a new array of given shape of input array, filled with ones.

In [8]:
array_2D = np.array([(3,4,6),(2,1,6)])
np.ones_like(array_2D)

array([[1, 1, 1],
       [1, 1, 1]])

###  `zeros`

In [11]:
# Creating array of zeros
np.zeros(4, dtype = np.int)

array([0, 0, 0, 0])

In [9]:
# Create a 3 X 4 integer array filled with zeros
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
# Create a 4 X 5 integer array filled with zeros
np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### arange
`arange` returns evenly spaced values within a given interval. Example: you want to create a one dimentional array with numbers between 0 and 30 in increments of 2

In [6]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [13]:
# np.arange()
# np.arange() is the numpy equivalent of range()
# Notice that 10 is included, 100 is not, as in standard python lists

# From 10 to 100 with a step of 5
numbers = np.arange(10, 100, 5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### linspace
With floating point increment, using `linspace` function, specify the start of the range, the end of the range, and then the total number of elements that you want your array to have

`linspace` returns evenly spaced numbers over a specified interval.

In [7]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
# np.linspace()
# Sometimes, you know the length of the array, not the step size

# Array of length 25 between 15 and 18
np.linspace(15, 18, 25)

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

### Create diagonal arrays
* `np.eye()`: Create a square NxN identity matrix (1s on the diagonal and 0s elsewhere)
* `np.identity()`: Create a square NxN identity matrix (1s on the diagonal and 0s elsewhere)
* `np.diag()`: Extracts a diagonal or constructs a diagonal array.

#### `eye`
Identity matrices are very useful when dealing with linear algebras. Usually, is a two-dimensional square matrix. This means the number of row is equal to the number of column. One unique thing to note about identity matrix is that the diagonals are 1’s and everything else is 0. Identity matrices usually takes a single argument. Here’s how to create one.

`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### `identity`

In [12]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### `diag`

In [ ]:
y = np.array([4, 5, 6])
np.diag(y)

#### `triu`

In [14]:
np.triu(np.ones((3, 3)), 1)  # Upper triangle of an array

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

#### `tril`

In [16]:
np.tril(np.ones((3, 3)), 1)  # Lower triangle of an array

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Create random matrix
We can generate an array of random numbers using `rand()`, `randn()` or `randint()` functions.

* `np.random.rand()`: Generate an array of random numbers of the shape we pass to it from uniform distribution over 0 to 1.
* `np.random.randn()`: Generate random samples from Standard, normal or Gaussian distribution centered around 0
* `np.random.random()`: Create array of random numbers
* `np.random.randint()`: Create a random array of integers within a particular range. The `randint()` function can take up to 3 arguments; the low(inclusive), high(exclusive) and size of the array.

#### `rand`

In [18]:
a = np.random.rand(4)  # uniform in [0, 1]
a

array([0.78845053, 0.67897355, 0.65241962, 0.07868705])

#### `randn`

In [17]:
b = np.random.randn(4)   # Gaussian
b

array([ 1.30270213, -0.89651192,  0.27185342, -1.80659933])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

#### `random`

In [7]:
# Array of random numbers
np.random.random([3, 4])

array([[0.86373949, 0.5700876 , 0.98172829, 0.02964714],
       [0.71756017, 0.98979163, 0.91946655, 0.20515467],
       [0.62962011, 0.23459724, 0.33405921, 0.36100961]])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3)) 

#### `randint`

In [5]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 2, 2],
       [2, 1, 1],
       [3, 2, 9]])

In [6]:
# create another matrix
np.random.randint(0, 10, (3, 3))

array([[7, 0, 3],
       [4, 2, 8],
       [3, 3, 9]])

In [19]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[1, 8, 4, 4],
       [7, 2, 4, 6],
       [3, 9, 9, 2],
       [1, 2, 8, 1]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

#### Fixing the seed
We got a different matrix when we generated another random matrix.

We can get the same matrix again by fixing the seed. Let's see how?

In [7]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [8]:
# fixing the random seed
np.random.seed(0)
np.random.randint(0, 10, (3, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

### Create a matrix of filled with any specific number of specific dimension.

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

* `np.full()`: Produce an array of the given shape and data type with all values set to the indicated "fill value"
* `np.full_like()`: Takes another array and produces a filled array of the same shape and data type

In [15]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [13]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### Create an empty array
* `np.empty()`: Create new arrays by allocating new memory, but do not populate with any values likes `ones` and `zeros`
* `np.empty_like()`: 

In [3]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
g = np.empty((3,3))
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create array by repeat another array
* `np.tile()`: Create a new array by repeating an existing array for a particular number of times
* `np.repeat()`: Create an array using repeating list

In [16]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [17]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [10]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## Copying Arrays
***Be careful with copying and modifying arrays in NumPy!***

In [53]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

`r2` is a slice of `r`

In [54]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice's values to zero ([:] selects the entire array)

In [55]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` has also been changed!

In [56]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

To avoid this, use `r.copy` to create a copy that will not affect the original array

### Views (or shallow copy)

In [5]:
# Create a view of the array with the same data
a = np.array([1,2,3])
h = a.view()

In [31]:
countries = np.array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'])
loc_1 = countries.view()
loc_2 = countries.view()

In [32]:
loc_1

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

In [33]:
loc_2

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

In [34]:
np.may_share_memory(loc_1,loc_2)

True

In [35]:
print('IDs for the Arrays are Differenct: ')
print('\nID for the countries is :', id(countries))
print('\nID for the loc views are :', id(loc_1))
print('\nID for the loc views are :', id(loc_2))

IDs for the Arrays are Differenct: 

ID for the countries is : 2306297553712

ID for the loc views are : 2306297555440

ID for the loc views are : 2306297553616


In [36]:
loc_1 is countries

False

In [37]:
loc_1.base is countries

True

What happen if we change the view?

In [38]:
loc_1 = np.array(['France', 'Iran', 'Australia', 'Mexico', 'Cuba', 'Egypt'])
loc_1

array(['France', 'Iran', 'Australia', 'Mexico', 'Cuba', 'Egypt'],
      dtype='<U9')

In [39]:
countries

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

What happen if we change the shape of view?

In [40]:
loc_2.shape = 2,3
print('Shape of loc_2: ', loc_2.shape)
print('Contents: \n', loc_2)

Shape of loc_2:  (2, 3)
Contents: 
 [['India' 'Peru' 'USA']
 ['Nigeria' 'Pakistan' 'Germany']]


In [41]:
print('Shape of the countries array : ', countries.shape)
print('Contents:\n', countries)

Shape of the countries array :  (6,)
Contents:
 ['India' 'Peru' 'USA' 'Nigeria' 'Pakistan' 'Germany']


### Deep Copies of Arrays

In [6]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [7]:
# Create a deep copy of the array
h = a.copy()

In [42]:
countries = np.array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'])
loc = countries.copy()
loc 

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

In [43]:
np.may_share_memory(countries, loc)

False

What happend if we change the content of the copies?

In [44]:
loc[0] = 'Turkey'
loc

array(['Turkey', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

In [45]:
countries

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')

In [46]:
loc.shape = 2,3

In [47]:
print('Contents of loc : ')
print(loc)

Contents of loc : 
[['Turkey' 'Peru' 'USA']
 ['Nigeria' 'Pakistan' 'Germany']]


In [48]:
countries

array(['India', 'Peru', 'USA', 'Nigeria', 'Pakistan', 'Germany'],
      dtype='<U8')