In [1]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

In [23]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


***# Reversed array a***

In [4]:
a = np.array([1,2,3])
a[ : :-1]

array([3, 2, 1])

***Select elements from a less than 2***

In [6]:
a[a<2]

array([1, 2])

In [25]:
# Iterations are also similar to lists
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```. 

Each axes has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.

<img src="2_d_array.png" style="width: 350px; height: 300px">


In [11]:
# Creating a 2-D array
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [12]:
# Third row second column
print(array_2d[2, 1])

12


In [13]:
# Slicing the second row, and all columns
# Notice that the resultant is itself a 1-D array
print(array_2d[1, :])
print(type(array_2d[1, :]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [14]:
# Slicing all rows and the third column
print(array_2d[:, 2])

[ 7  8 15]


In [15]:
# Slicing all rows and the first three columns
print(array_2d[:, :3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


***Fancy Indexing***

In [7]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [8]:
# Select a subset of the matrix’s rows and columns
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

**Iterating on 2-D arrays** is done with respect to the first axis (which is row, the second axis is column). 

In [16]:
# Iterating over 2-D arrays
for row in array_2d:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [17]:
# Iterating over 3-D arrays: Done with respect to the first axis
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
# Prints the two blocks
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
