![Numpy_axes_shaping](../images/Numpy_axes_shaping.PNG)

In [2]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

### Subset, Slice, Index and Iterate through Arrays

For **one-dimensional arrays**, indexing, slicing etc. is **similar to python lists** - indexing starts at 0.

# Subset / Slicing

In [23]:
# Indexing and slicing one dimensional arrays
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

## Slicing 1-diamention array
To access subarrays with the slice notation, marked by the colon (:) character.

`array[start:stop:step]`, leaving `start` or `stop` empty will default to the beginning/end of the array.

In [8]:
s = np.arange(13)**2   #1D array

s[-4:]  # Use negatives to count from the back.
s[-5::-2] # Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.
s[::-1]   # Quickly get the reversed contents of a numpy array called "array"

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [24]:
# Third element
print(array_1d[2])

# Specific elements
# Notice that array[2, 5, 6] will throw an error, you need to provide the indices as a list
print(array_1d[[2, 5, 6]])

# Slice third element onwards
print(array_1d[2:])

# Slice first three elements
print(array_1d[:3])

# Slice third to seventh elements
print(array_1d[2:7])

# Subset starting 0 at increment of 2 
print(array_1d[0::2])

2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


## Slicing multidimensional 
Let's look at a multidimensional array. Use bracket notation to slice: `array[row, column]`

In [10]:
x = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]]) # 2D array

x[2, 2]
x[2, 0:1]  # use : to select a range of rows or columns
x[:2, :3]  # two rows, three columns
x[:2, :-1] # Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.
x[-1, ::2] # This is a slice of the last row, and only every other element.
x[:, 0]    # Accessing single rows or columns of an array: first column
x[0, :]    # Accessing single rows or columns of an array: first row
x[x > 30]  # We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see np.where)
x

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [11]:
x[x > 30] = 30
x

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x_sub = x[:2, :2]
x_sub

array([[3, 5],
       [7, 6]])

In [13]:
x_sub[0,0] = 99
print(x_sub)
print(x)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reversed array

In [4]:
a = np.array([1,2,3])
a[ : :-1]

array([3, 2, 1])

***Select elements from a less than 2***

In [6]:
a[a<2]

array([1, 2])

In [25]:
# Iterations are also similar to lists
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


**Multidimensional arrays** are indexed using as many indices as the number of dimensions or axes. For instance, to index a 2-D array, you need two indices - ```array[x, y]```. 

Each axes has an index starting at 0. The following figure shows the axes and their indices for a 2-D array.

<img src="../images/2_d_array.png" style="width: 350px; height: 300px">


In [11]:
# Creating a 2-D array
array_2d = np.array([[2, 5, 7, 5], [4, 6, 8, 10], [10, 12, 15, 19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [12]:
# Third row second column
print(array_2d[2, 1])

12


In [13]:
# Slicing the second row, and all columns
# Notice that the resultant is itself a 1-D array
print(array_2d[1, :])
print(type(array_2d[1, :]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [14]:
# Slicing all rows and the third column
print(array_2d[:, 2])

[ 7  8 15]


In [15]:
# Slicing all rows and the first three columns
print(array_2d[:, :3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


# Indexing
## Fancy Indexing

In [7]:
# Select elements (1,0),(0,1),(1,2) and (0,0)
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [8]:
# Select a subset of the matrix’s rows and columns
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

**Iterating on 2-D arrays** is done with respect to the first axis (which is row, the second axis is column). 

In [16]:
# Iterating over 2-D arrays
for row in array_2d:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [17]:
# Iterating over 3-D arrays: Done with respect to the first axis
array_3d = np.arange(24).reshape(2, 3, 4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
# Prints the two blocks
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Boolean Indexing
**Goal:** create a new array that contains a fine-grained element selection of the old array

We create two arrays “a” and “indices”. The first array contains two-dimensional numerical data (=data array). The second 
array has the same shape and contains Boolean values (=indexing array). You can use the indexing array for finegrained data array access. This creates a new NumPy array from the data array containing only those elements for which the indexing array contains “True” Boolean values at the respective array positions. Thus, the resulting array contains the three values 3, 7, and 8.


In [1]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

indices = np.array([[False,False,True],
                    [False,False,False],
                    [True,True,False]])

print(a[indices])

[3 7 8]


# Reshape
## reshape
`reshape` returns an array with the same data with a new shape. Reshape to specify array dimensions for an automatic sequence

**Note**: The `reshape()` can only convert to equal number or rows and columns and must together be equal to equal to the number of elements.

Create matrix using np.reshape function:
* Third parameter:
    * "C": c style - fill data row by row
    * "F": Fortran language like - fill data column by column

In [ ]:
mydata = np.arange(0, 20)
A = np.reshape(mydata, [5, 4])
A

In [ ]:
np.reshape(mydata, (5, 4), order='C')

In [ ]:
np.reshape(mydata, (5, 4), order='F')

In [ ]:
mydata.reshape((4, 5))

In [4]:
tech_companies = np.array([('IMB','Apple Inc.', 'Intel', 'Dell', 'Microsoft'),
                          ('New York', 'California', 'California', 'Texas', 'Washington')])
tech_companies

array([['IMB', 'Apple Inc.', 'Intel', 'Dell', 'Microsoft'],
       ['New York', 'California', 'California', 'Texas', 'Washington']],
      dtype='<U10')

In [ ]:
tech_companies.shape

In [ ]:
tech_companies.reshape(2,5)

In [ ]:
tech_companies.reshape(-1,2)

In [ ]:
tech_companies.reshape(2,-1)

In [ ]:
3*int(tech_companies.shape[0]/3)

In [ ]:
sample_=tech_companies[0:3*int(tech_companies.shape[0]/3)]
sample_

In [ ]:
x = np.array([1, 2, 3])
x[np.newaxis, :]  # row vector via newaxis
x.reshape((3, 1)) # column vector via reshape
x[:, np.newaxis]  # column vector via newaxis

## Flatten

### Flattens 2D array to 1D

In [14]:
tech_companies.flatten()

array(['IMB', 'Apple Inc.', 'Intel', 'Dell', 'Microsoft', 'New York',
       'California', 'California', 'Texas', 'Washington'], dtype='<U10')

### ravel

In [5]:
# similar to flatten function
# The difference is ravel() belong to an array object, while flatten() 
tech_companies.ravel()

array(['IMB', 'Apple Inc.', 'Intel', 'Dell', 'Microsoft', 'New York',
       'California', 'California', 'Texas', 'Washington'], dtype='<U10')