# Operations on NumPy Arrays

The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


### Manipulating Arrays

Let's look at some ways to manipulate arrays, i.e. changing the shape, combining and splitting arrays, etc.   

#### Reshaping Arrays

Reshaping is done using the ```reshape()``` function.


In [3]:
import numpy as np

# Reshape a 1-D array to a 3 x 4 array
some_array = np.arange(0, 12).reshape(3, 4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
# Can reshape it further 
some_array.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [3]:
# If you specify -1 as a dimension, the dimensions are automatically calculated
# -1 means "whatever dimension is needed" 
some_array.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
# Flatten the array
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

---
***Array Concatenation :***


---



In [ ]:
# concatenating 2-D arrays
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print("matrix 1")
matrix1

In [ ]:
matrix2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])
print("matrix 2",)
matrix2

***Concatenate Row wise***

---

In [ ]:
# concatenate along the first axis
matrix_1_2_combineRowwise = np.concatenate([matrix1, matrix2],axis=0)
print("Combined on Row (axis=0)")
matrix_1_2_combineRowwise

***Concatenate Column wise***


---

In [ ]:
# concatenate along the second axis (zero-indexed)
matrix_1_2_combineColwise = np.concatenate([matrix1, matrix2], axis=1)
print("Combined on Col (axis=1)")
matrix_1_2_combineColwise

### Stacking and Splitting Arrays

#### Stacking: ```np.hstack()``` and ```n.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

In [5]:
# Creating two arrays
array_1 = np.arange(12).reshape(3, 4)
array_2 = np.arange(20).reshape(5, 4)

print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [6]:
# vstack
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list
np.vstack((array_1, array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Similarly, two arrays having the same number of rows can be horizontally stacked using ```np.hstack((a, b))```.

### Sorting Arrays

In [5]:
# Sort an array
some_array.sort()

In [9]:
# Sort the elements of an array's axis
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c.sort(axis=0)

### Transposing Array

In [14]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [17]:
# Permute array dimensions
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

```array.T``` returns the transpose of an array.

In [16]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
# Transposing an array
some_array.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])