# Operations on NumPy Arrays

The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


In [2]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

### Perform Operations on Arrays

Performing mathematical operations on arrays is extremely simple. Let's see some common operations.


#### Basic Mathematical Operations

NumPy provides almost all the basic math functions - exp, sin, cos, log, sqrt etc. The function is applied to each element of the array.


In [3]:
# Basic mathematical operations
a = np.arange(1, 20)

# sin, cos, exp, log
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


### Arithmetic Operations

In [3]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

#### Scalar math

In [7]:
# Add 1 to each array element
np.add(b,1)

array([[2.5, 3. , 4. ],
       [5. , 6. , 7. ]])

In [8]:
# Substract 2 from each array element
np.subtract(b,2)

array([[-0.5,  0. ,  1. ],
       [ 2. ,  3. ,  4. ]])

In [10]:
# Multiple each array element by 3
np.multiply(b,3)

array([[ 4.5,  6. ,  9. ],
       [12. , 15. , 18. ]])

In [11]:
# Devide each array element by 4 (return np.nan for division by zero)
np.divide(b,4)

array([[0.375, 0.5  , 0.75 ],
       [1.   , 1.25 , 1.5  ]])

In [12]:
# Raise each array element to the 5th power
np.power(b,5)

array([[7.59375e+00, 3.20000e+01, 2.43000e+02],
       [1.02400e+03, 3.12500e+03, 7.77600e+03]])

#### Vector math

##### Subtraction

In [5]:
g = a - b
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [6]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

***Addition***

In [7]:
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [8]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

***Division***

In [9]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [10]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

***Multiplication***

In [11]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [12]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

***Exponentiation***

In [13]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

***Square root***

In [14]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

***Print sines of an arra***

In [15]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

***Element-wise cosine***

In [16]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

***Element-wise natural logarithm***

In [17]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

***Dot product***

In [18]:
e = np.full((2,2),7)
f = np.eye(2)

In [19]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

***Power each element in array***

In [4]:
np.power(a, 5)

array([      1,      32,     243,    1024,    3125,    7776,   16807,
         32768,   59049,  100000,  161051,  248832,  371293,  537824,
        759375, 1048576, 1419857, 1889568, 2476099], dtype=int32)

### Comparison

***Element-wise comparison***

In [20]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [21]:
a < 2

array([ True, False, False])

***Array-wise comparison***

In [22]:
np.array_equal(a, b)

False

### Aggregate Functions

In [23]:
# Array-wise sum
a.sum()

6

In [24]:
# Array-wise minimum value
a.min()

1

In [25]:
# Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [26]:
# Cumulative sum of the elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [27]:
# Mean
a.mean()

2.0

In [28]:
# Median
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [29]:
# Correlation coefficient
a.corrcoef() 

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [30]:
# Standard deviation
np.std(b) 

1.5920810978785667