In [2]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

# Scalar math

In [3]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

Add 1 to each array element

In [4]:
np.add(b,1)

array([[2.5, 3. , 4. ],
       [5. , 6. , 7. ]])

Substract 2 from each array element

In [8]:
np.subtract(b,2)

array([[-0.5,  0. ,  1. ],
       [ 2. ,  3. ,  4. ]])

Multiple each array element by 3

In [10]:
np.multiply(b,3)

array([[ 4.5,  6. ,  9. ],
       [12. , 15. , 18. ]])

Devide each array element by 4 (return np.nan for division by zero)

In [11]:
np.divide(b,4)

array([[0.375, 0.5  , 0.75 ],
       [1.   , 1.25 , 1.5  ]])

Raise each array element to the 5th power

In [12]:
np.power(b,5)

array([[7.59375e+00, 3.20000e+01, 2.43000e+02],
       [1.02400e+03, 3.12500e+03, 7.77600e+03]])