## Array Broadcasting
### What is Broadcasting?
Goal: bring arrays with different shapes into the same shape during arithmetic operations. NumPy does that for you

### Understanding Array Broadcasting
We worked with many array element-by-element. This works quite seamlessly when the two arrays being operated upon have the same dimensions. However, there will be occasions when we need to perform operations between two arrays which do not share the same shape. This is where we need to use the concept of `bradcasting` in order to perform operations between mismatched arrays. 

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

Describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **"broadcast"** across the larger array so that they have compatible shapes.

It is performed on pairs of arrays on an **element-by-element basis**.

So `broadcasting` is a technique where we can perform arithmetic or other operations between two arrays, where the shape are different. And this works, in effect, by broadcasting the smaller array 
until it matches the size of the larger array. 

Do note that broadcasting will not work with every single array, and that there are certain restrictions on the shapes of the arrays. However, the two arrays which are being operated upon need not be of extractly the same shape. 

#### Compatibility in Broadcasting
* Broadcasting scalars - Operations between scalars and arrays are always possible - the scalar is broadcast over the array
* Broadcasting arrays - Operations between two arrays be possible only under certain conditions

What types of broadcasting is possible in NumPy? 

If we are performing an operation between a NumPy array and a scalar quantity, then broadcasting will always work. And this is because the scalar will simply be broadcast across the entire array it is being operated with. 

When we are performing an operation between two arrays of different shapes, then the smaller array is effectively broadcast across the entire larger array.  However, this only works under specific conditions.

#### Broadcasting Scalars

**For any dimension where first array has size of one, NumPy conceptually copies its data until the size of the second array 
is reached. **

Consider a multiplication operation which we perform between one dimentionarray of 8 elements, with a scalar quantity of 20

![Image of Broaddcasting](../images/broadcastingScalars.PNG)



So in this case, we have some_array which has 8 elements. In order to perform an element-by-element multiplication, it needs 8 other elements, and in the case with the scalar, we only have one.  

<img src="../images/broadcastingScalars1.PNG">

This is where the scalar need to be broadcast across the entire array it is being operated with. you can think of this as NumPy creating an array which has the same shape as the array being operated with, and each element of this array will have the same value as the scalar quantity. 

<img src="../images/broadcastingScalars2.PNG">

So in this case we end up with two arrays of compatible shapes, and we can perform an element-by-element multiplication, in order to give such a result. So when some-array is multiplied with some_scalar, then the results is an array which has the same shape as some_array. Operations with scalars also work with multidimensional arrays, but the scalar is simply broadcast to the shape of the array it is being operated with. So this is how broadcasting works between arrays and scalars. 

<img src="../images/broadcastingScalars3.PNG">

#### Broadcasting Arrays

**If dimension is completely missing for array B, it is simply copied along the missing dimension.**

So arithmetic operations are performed between pairs of arrays with the same shape on an element-by-element basis. While there are no restrictions when it comes to broadcasting scalars, broadcasting of arrays only takes place under certain constraints.

To be precise, two arrays are set to be compatible for broadcasting, after the shapes of these two arrays are compared on an element-by-element basis. Consider below cases:

* Case 1:
<img src="../images/broadcastingScalars4.PNG">

The single column of the array on the right can be broadcast eight times, in order to match the shape of the array on the 
left. 

<img src="../images/broadcastingScalars5.PNG">

* Case 2:
<img src="../images/broadcastingScalars6.PNG">

`=====> These two array is not compatible`

* Case 3: 
<img src="../images/broadcastingScalars7.PNG">

`=====> These two array is not compatible`

So the broadcasting of the smaller array only works when the corresponding dimensions of the two arrays being operated upon are compatible. That is, these arrays have compatible shapes. **Two dimensions are said to be compatible when they are either identical, or when one of those two dimensions is equal to 1**. 

So broadcasting provides a lot of flexibility when working with NumPy arrays:
* Allows arrays of different shapes to be combined 
* Memory-efficient as needless copies avoided -> by not creating multiple copies of the smaller array, broadcasting is also very memory efficient. 
* Computationally-efficient, operations performed in C rather than Python. Under the hood, a lot of the broadcasting operations are implemented in C rather than in Python, which make it very compurationally efficient as well. 

We will try to replicating the smaller array to fit the shape of the larger array. 
In other words, the smaller aray is broadcast until it matches the shape of the larger one. 

In [5]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([5, 5, 5, 5, 5])
z = 10

In [4]:
# This is element-by-element multiplication
x * y

array([10, 20, 30, 40, 50])

In [6]:
x * z

array([ 20,  40,  60,  80, 100])

In [7]:
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
ones * z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [9]:
top_speeds = [184, 243, 192, 309, 257, 218]
weights = [1178, 1243, 1403, 1047, 1673, 1375]

In [10]:
car_info = np.array([top_speeds, weights])
car_info

array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1403, 1047, 1673, 1375]])

In [15]:
conversion_factors = np.array([0.621371, 2.20462])
conversion_factors

array([0.621371, 2.20462 ])

In [12]:
conversion_factors.shape

(2,)

In [13]:
car_info.shape

(2, 6)

In [14]:
car_info * conversion_factors

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [16]:
new_factors = conversion_factors.reshape(2,1)
new_factors

array([[0.621371],
       [2.20462 ]])

In [17]:
car_info * new_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 3093.08186 , 2308.23714 , 3688.32926 ,
        3031.3525  ]])

# Vector Math

In [2]:
# Import the numpy library
# np is simply an alias, you may use any other alias, though np is quite standard
import numpy as np

In [10]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
d = np.array([1,-2,3,-4,5,-6])
e = np.array([10.45, 9.12,7.38,8.56])

## Addition

In [4]:
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [5]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

## Subtraction

In [ ]:
g = a - b
print(g)

In [ ]:
np.subtract(a,b)

## Multiplication

In [ ]:
a * b

In [ ]:
np.multiply(a,b)

## Division

In [ ]:
a / b

In [ ]:
np.divide(a,b)

## sin, cos, log, exp, sqrt

In [17]:
a = np.arange(1, 20)
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


### Element-wise sines

In [ ]:
np.sin(a)

### Element-wise cosine

In [ ]:
np.cos(b)

### Element-wise natural logarithm

In [ ]:
np.log(a)

### Exponentiation

In [ ]:
np.exp(b)

### Square root

In [6]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## Absolute
Absolute value of each element in the array

In [9]:
np.abs(d)

array([1, 2, 3, 4, 5, 6])

### Rounds up
Rounds up to the nearest int

In [13]:
e

array([10.45,  9.12,  7.38,  8.56])

In [11]:
np.ceil(e)

array([11., 10.,  8.,  9.])

## Rounds down
Rounds down to the nearest int

In [14]:
e

array([10.45,  9.12,  7.38,  8.56])

In [12]:
np.floor(e)

array([10.,  9.,  7.,  8.])

##  Rounds down to the nearest int

In [15]:
e

array([10.45,  9.12,  7.38,  8.56])

In [16]:
np.round(e)

array([10.,  9.,  7.,  9.])

### Comparisons
We can compare complete arrays of equal size element wise

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [19]:
a == b

array([False,  True, False,  True])

In [20]:
a > b

array([False, False,  True, False])

Array-wise comparisons

In [21]:
np.array_equal(a, b)

False

In [22]:
np.array_equal(a, c)

True

`allclose()` will return True if items in two arrays are equal within a tolerance. It will provide you with a great way of checking if two arrays are similar, which can in some cases be a pain in the bottom to implement manually.

In [23]:
arr1 = np.array([0.15, 0.20, 0.25, 0.17])
arr2 = np.array([0.14, 0.21, 0.27, 0.15])

In [24]:
np.allclose(arr1, arr2, 0.1)

False

In [25]:
np.allclose(arr1, arr2, 0.2)

True

### Logical operations

In [ ]:
np.logical_or(a, b)

In [ ]:
np.logical_and(a, b)

### Dot Product:

(|x_1 | x_2 | x_3 |).dot(|y_1 | y_2 | y_3 |)
= x_1 * y_1 + x_2 * y_2 + x_3 * y_3

These below will return result in identical.

In [7]:
e = np.full((2,2),7)
print(e)
f = np.eye(2)
print(f)
e.dot(f)
print(e)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[7 7]
 [7 7]]


In [ ]:
x = np.arange(1, 6)

x.dot(y) # dot product  1*4 + 2*5 + 3*6
np.dot(x, y) # dot product  1*4 + 2*5 + 3*6
z = np.array([y, y**2])
print(len(z)) # number of rows of array

Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [ ]:
z = np.array([y, y**2])
z

In [ ]:
#Create vector-1
vector_1 = np.array([ 1,2,3 ])
#Create vector-2
vector_1 = np.array([ 4,5,6 ])
#Calculate Dot Product
print(np.dot(vector_1,vector_2))
#Alternatively you can use @ to calculate dot products
print(vector_1 @ vector_2)